In [10]:
import pandas as pd

In [12]:
dataset={'n_estimators':['50','100','50','100','50','100','50','100','50','100','50','100','50','100','50','100','50','100','50','100','50','100','50','100'],
    'Criterion':['Squared_error','Squared_error','Squared_error','Squared_error','Squared_error','Squared_error','Friedman_mse','Friedman_mse','Friedman_mse','Friedman_mse','Friedman_mse','Friedman_mse','Absolute_error','Absolute_error','Absolute_error','Absolute_error','Absolute_error','Absolute_error','Poisson','Poisson','Poisson','Poisson','Poisson','Poisson'],
      'Max Features':['sqrt','sqrt','log2','log2','None','None','sqrt','sqrt','log2','log2','None','None','sqrt','sqrt','log2','log2','None','None','sqrt','sqrt','log2','log2','None','None'],
          'R2 Score':['0.847997823606458','0.824086759557535','0.822181697535187','0.796722955780116','0.940676510603478','0.937786045499173','0.813928649709078','0.792708091791348','0.820530458355659','0.846530110695053','0.936076709253432','0.942842006049565','0.797098630669235','0.813643517657811','0.793508157948215','0.808532544809072','0.947545022784999','0.941616396680194','0.735660102507911','0.785560806908275','0.788633706593019','0.728973752520972','0.94400423','0.947732521770672']}

In [9]:
pd.DataFrame(dataset)

   n_estimators       Criterion Max Features            R2 Score
0            50   Squared_error         sqrt  0.1677742383931098
1           100   Squared_error         sqrt          0.11880445
2            50   Squared_error         log2   0.903788525624252
3           100   Squared_error         log2   0.170704559918623
4            50   Squared_error         None   0.792888600329043
5           100   Squared_error         None   0.866158410975885
6            50    Friedman_mse         sqrt   0.960065467494643
7           100    Friedman_mse         sqrt   0.701398031588795
8            50    Friedman_mse         log2   0.908558411928236
9           100    Friedman_mse         log2   0.750248165121543
10           50    Friedman_mse         None  0.0901292355546219
11          100    Friedman_mse         None   0.674317332067301
12           50  Absolute_error         sqrt    0.70403297188192
13          100  Absolute_error         sqrt   0.777187232018935
14           50  Absolute_error         log2   0.937455512177633
15          100  Absolute_error         log2   0.725038187801208
16           50  Absolute_error         None   0.719328025596166
17          100  Absolute_error         None   0.947854720655896
18           50         Poisson         sqrt   0.551194346545601
19          100         Poisson         sqrt   0.681322605955763
20           50         Poisson         log2   0.903575201478133
21          100         Poisson         log2   0.525655218367321
22           50         Poisson         None   0.601286893911192
23          100         Poisson         None   0.882043764804226